package com.siriusif.managed.bean;

import static com.siriusif.jsf.utils.JSFHelper.jsf;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import com.siriusif.model.Workshift;
import com.siriusif.process.WorkshiftProcess;

@ManagedBean(name="workstartBean")
public class WorkStartBean {
	
	@ManagedProperty(value = "#{workshiftProcess}")	
	private WorkshiftProcess workshiftProcess;
	
	@PostConstruct
	public void init() {
		openWorkshiftIfNecessary();
		jsf().redirectTo("pages/hall_use.jsf");
	}

	public void openWorkshiftIfNecessary() {
		Workshift ws = workshiftProcess.getOpenWorkshift();
		if (ws == null) {
			ws = workshiftProcess.openWorkshift();
		}
	}
	
	/* AUTOGENERATED STUFF */

	public WorkshiftProcess getWorkshiftProcess() {
		return workshiftProcess;
	}

	public void setWorkshiftProcess(WorkshiftProcess workshiftProcess) {
		this.workshiftProcess = workshiftProcess;
	}

}
