package com.siriusif.model;

import javax.persistence.Column;

/**
 * I use this class to handle process methods.
 * Domain need to know who perform operation
 * @author sbelei
 *
 */
// TODO SB : Copied from User class. 
public class Credentials {
	
	/** user login */
	@Column(name="name", nullable=false, length=100)
	private String login;
	
	/** user password */
	@Column(name="psw", nullable=false, length=100)
	private String password;
	
	/* autogenerated stuff */

	/**
	 * @return the login
	 */
	public String getLogin() {
		return login;
	}

	/**
	 * @param login the login to set
	 */
	public void setLogin(String login) {
		this.login = login;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

}
