package com.siriusif.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity
@Table(name = "`dining_table`")
public class DinnerTable {
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private Long id;
	
	/**
	 * name of table
	 */
	@Column(name="`name`", nullable=false, length=100)
	private String name;
	
	/**
	 * description of table
	 */
	@Column(name="`description`", nullable=true, length=100)
	private String description;
	
	/**
	 * location of table(distance from the top)
	 */
	@Column(name = "`ctop`", nullable = true)
	private int top;
	
	// left is reserved word in SQL
	/**
	 * location of table(distance from the left)
	 */
	@Column(name = "`cleft`", nullable = true)
	private int left;
	
	/**
	 * height of table
	 */
	@Column(name = "`height`", nullable = true)
	private int height;
	
	/**
	 * width of table
	 */
	@Column(name = "`width`", nullable = true)
	private int width;
	
	@ManyToOne
	@JoinColumn(name = "`hall_id`")
	private Hall hall;
	
	@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy = "table")
	private List<Order> orders;
	
	public DinnerTable(){
		orders = new ArrayList<Order>();
	}
	
	public DinnerTable(String name, String description, int left, int top) {
		this();
		this.name = name;
		this.description = description;
		this.left = left;
		this.top = top;
	}
	
	public void addOrder(Order order){
		order.setTable(this);
		orders.add(order);
	}

	/*
	 * this method is created for GUI purposes
	 */
	public int getBottom() {
		return top+height;
	}
	
	/*
	 * this method is created for GUI purposes
	 */
	public int getRight() {
		return left+width;
	}
	
	/* autogenerated stuff */
	
	
	public Hall getHall() {
		return hall;
	}
	public void setHall(Hall hall) {
		this.hall = hall;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public int getTop() {
		return top;
	}
	public void setTop(int top) {
		this.top = top;
	}
	public int getLeft() {
		return left;
	}
	public void setLeft(int left) {
		this.left = left;
	}
	public int getHeight() {
		return height;
	}
	public void setHeight(int height) {
		this.height = height;
	}
	public int getWidth() {
		return width;
	}
	public void setWidth(int width) {
		this.width = width;
	}

	public List<Order> getOrders() {
		return orders;
	}

	public void setOrders(List<Order> orders) {
		this.orders = orders;
		for(Order order : orders){
			order.setTable(this);
		}
	}

}
