package com.siriusif.model;


import java.math.BigDecimal;
import java.math.RoundingMode;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "good")
public class Good {
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private Long id;
	
	@Column(name = "art", nullable = true)
	private Long art;
	
	@Column(name="name", nullable=false, length=100)
	private String name;
	
	@Column(name="price", nullable = false, precision=16, scale=2)
	private BigDecimal price;
	
	@Column(name="kitchen", columnDefinition="boolean default false") 
	private boolean kitchen;
	
	@Column(name="bar", columnDefinition="boolean default false") 
	private boolean bar;
	
	@Column(name="pdv", columnDefinition="boolean default false") 
	private boolean pdv;
	
	@Column(name="weight", columnDefinition="boolean default false") 
	private boolean weight;
	
	@Column(name="shortname", nullable=false, length=100)
	private String shortName;
	
	@Column(name="piece", columnDefinition="boolean default false") 
	private boolean piece;
	
	@Column(name="minprice", nullable = true, precision=16, scale=2)
	private BigDecimal minPrice;
	
	@Column(name="billiard", columnDefinition="boolean default false") 
	private boolean billiard;
	
	@Column(name = "kitchenPrinterId", nullable = true)
	private int kitchenPrinterId;
	
	@Transient
	private Group parentGroup;
	
	public Good(){
		price = BigDecimal.ZERO;
	}
	
	public Good(String name, BigDecimal price) {
		this();
		this.name = name;
		this.price = price;
	}
	
	/* autogenerated stuff */
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getArt() {
		return art;
	}
	public void setArt(Long art) {
		this.art = art;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public BigDecimal getPrice() {
		 //TODO CS : Scale hardcoded!!!
	
		return price;
	}
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	public boolean isKitchen() {
		return kitchen;
	}
	public void setKitchen(boolean kitchen) {
		this.kitchen = kitchen;
	}
	public boolean isBar() {
		return bar;
	}
	public void setBar(boolean bar) {
		this.bar = bar;
	}
	public boolean isPdv() {
		return pdv;
	}
	public void setPdv(boolean pdv) {
		this.pdv = pdv;
	}
	public boolean isWeight() {
		return weight;
	}
	public void setWeight(boolean weight) {
		this.weight = weight;
	}
	public String getShortName() {
		return shortName;
	}
	public void setShortName(String shortName) {
		this.shortName = shortName;
	}
	public boolean isPiece() {
		return piece;
	}
	public void setPiece(boolean piece) {
		this.piece = piece;
	}
	public BigDecimal getMinPrice() {
		//TODO CS : Scale hardcoded!!!
		minPrice.setScale(2, RoundingMode.HALF_UP);
		return minPrice;
	}
	public void setMinPrice(BigDecimal minPrice) {
		this.minPrice = minPrice;
	}
	public boolean isBilliard() {
		return billiard;
	}
	public void setBilliard(boolean billiard) {
		this.billiard = billiard;
	}
	public int getKitchenPrinterId() {
		return kitchenPrinterId;
	}
	public void setKitchenPrinterId(int kitchenPrinterId) {
		this.kitchenPrinterId = kitchenPrinterId;
	}
	public Group getParentGroup() {
		return parentGroup;
	}
	public void setParentGroup(Group parentGroup) {
		this.parentGroup = parentGroup;
	}
	

}
