package com.siriusif.model;


import java.math.BigDecimal;
import java.math.RoundingMode;


public class Good {
	private int id;
	private int art;
	private String name;
	private BigDecimal price;
	private boolean kitchen;
	private boolean bar;
	private boolean pdv;
	private boolean weight;
	private int group;
	private String shortName;
	private boolean piece;
	private BigDecimal minPrice;
	private boolean billiard;
	private int kitchenPrinterId;
	private Group parentGroup;
	
	public Good(String name, BigDecimal price) {
		this.name = name;
		this.price = price;
	}
	
	/* autogenerated stuff */
	
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public int getArt() {
		return art;
	}
	public void setArt(int art) {
		this.art = art;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public BigDecimal getPrice() {
		 //TODO CS : Scale hardcoded!!!
	
		return price;
	}
	public void setPrice(BigDecimal price) {
		this.price = price;
	}
	public boolean isKitchen() {
		return kitchen;
	}
	public void setKitchen(boolean kitchen) {
		this.kitchen = kitchen;
	}
	public boolean isBar() {
		return bar;
	}
	public void setBar(boolean bar) {
		this.bar = bar;
	}
	public boolean isPdv() {
		return pdv;
	}
	public void setPdv(boolean pdv) {
		this.pdv = pdv;
	}
	public boolean isWeight() {
		return weight;
	}
	public void setWeight(boolean weight) {
		this.weight = weight;
	}
	public int getGroup() {
		return group;
	}
	public void setGroup(int group) {
		this.group = group;
	}
	public String getShortName() {
		return shortName;
	}
	public void setShortName(String shortName) {
		this.shortName = shortName;
	}
	public boolean isPiece() {
		return piece;
	}
	public void setPiece(boolean piece) {
		this.piece = piece;
	}
	public BigDecimal getMinPrice() {
		//TODO CS : Scale hardcoded!!!
		minPrice.setScale(2, RoundingMode.HALF_UP);
		return minPrice;
	}
	public void setMinPrice(BigDecimal minPrice) {
		this.minPrice = minPrice;
	}
	public boolean isBilliard() {
		return billiard;
	}
	public void setBilliard(boolean billiard) {
		this.billiard = billiard;
	}
	public int getKitchenPrinterId() {
		return kitchenPrinterId;
	}
	public void setKitchenPrinterId(int kitchenPrinterId) {
		this.kitchenPrinterId = kitchenPrinterId;
	}
	public Group getParentGroup() {
		return parentGroup;
	}
	public void setParentGroup(Group parentGroup) {
		this.parentGroup = parentGroup;
	}
	

}
