package com.siriusif.model;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "groupofgood")
public class Group {
	@Id
	@GeneratedValue(strategy = GenerationType.TABLE)
	private int gId;
	
	@Column(name="name", nullable=false, length=100)
	private String gName;
	@Transient
	private List<Group> subGroups;
	@Transient
	private List<Good> goods;
	
	/** Group belongs to this parent group **/
	@Transient
	private Group parentGroup;
	
	public Group(){
		subGroups = new ArrayList<Group>();	
		goods = new ArrayList<Good>();
	}
	

	public Group(String gName) {
		this();
		this.gName = gName;
	}

	public void addSubGroup(Group subGroup) {
		subGroup.setParentGroup(this);
		subGroups.add(subGroup);
	}
	
	public void addGood(Good good) {
		good.setParentGroup(this);
		goods.add(good);
	}

	/* autogenerated stuff */
	
	public int getgId() {
		return gId;
	}
	public void setgId(int gId) {
		this.gId = gId;
	}
	public String getgName() {
		return gName;
	}
	public void setgName(String gName) {
		this.gName = gName;
	}

	public List<Good> getGoods() {
		return goods;
	}

	public void setGoods(List<Good> goods) {
		this.goods = goods;
	}
	
	public List<Group> getSubGroups() {
		return subGroups;
	}

	public void setSubGroups(List<Group> subGroups) {
		this.subGroups = subGroups;
	}

	private void setParentGroup(Group group) {
		parentGroup = group;
	}

	public Group getParentGroup() {
		return parentGroup;
	}


	
}
