package com.siriusif.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * User Entity
 * CREATE TABLE "Users" (
	"Name" NVARCHAR(10) NOT NULL,
	"Role" SMALLINT NOT NULL,
	"Psw" NVARCHAR(255) NOT NULL,
	"FullName" NVARCHAR(50) NULL
 */
@Entity
@Table(name="users")
public class User {

	@Id
	@GeneratedValue(strategy=GenerationType.TABLE)
	private Long id;
	
	/** user login */
	@Column(name="name", nullable=false, length=100)
	private String login;
	
	/** user role */
	@Column(name="role", nullable=false)
	private String role;
	
	/** user password */
	@Column(name="psw", nullable=false, length=100)
	private String password;
	
	/** full user name which displayed everywhere */
	@Column(name="fullName", nullable=false, length=100)
	private String name;
	
	
	/* autogenerated stuff */
	
	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}
	
	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}
	
	/**
	 * @return the login
	 */
	public String getLogin() {
		return login;
	}
	
	/**
	 * @param login the login to set
	 */
	public void setLogin(String login) {
		this.login = login;
	}
	
	/**
	 * @return the role
	 */
	public String getRole() {
		return role;
	}
	
	/**
	 * @param role the role to set
	 */
	public void setRole(String role) {
		this.role = role;
	}
	
	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}
}
